/* This is a generated file. To change it, edit function foxh() in fox.c */
#define _XOPEN_SOURCE
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <setjmp.h>
#include <memory.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <stdarg.h>
#include <math.h>
#include <time.h>
#include <assert.h>
#include <sys/time.h>
#include <regex.h>
#ifndef __MINGW32__
#include <execinfo.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#endif
#include <unistd.h>
#include <ctype.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>

#include <signal.h>
#include <sqlite3.h>
//	#include <openssl/md5.h>

enum Types {
	Null,Int,Double,String,Blob,Map,Vector,Index,Keys,Cell,Cell2,Tail
};
typedef struct Mapcell {
	short nextid;
	int hkey;
	char* id;
	void* val;
} Mapcell;
typedef struct map {
	int len;
	char type;
	union {
		struct Mapcell* pairs;
		void** vars;
	};
} map;

#define each_mem(pg,i) int i=0; for(mempage* pg=_gcdata.pages;i<_gcdata.total_pages;i++,pg=_gcdata.pages+i)
#define gc_start() void* __sp=NULL;init_gc(&__sp)
#define max(a,b) ((a)>(b)?(a):(b))
#define min(a,b) ((a)<(b)?(a):(b))
#ifdef __MINGW32__
#define is_i(x) ((int)(x)>>30 & 1)
#else
#define is_i(x) ((long long)(x)>>61 & 2)
#define is_f(x) ((*(long long*)&(x))>>61 & 1)
#define is_num(x) ((*(long long*)&(x))>>61 & 3)
#endif

typedef struct mempage {
	int no;
	int idx;
	int block_size;
	int blocks;
	int free;
	char* types;
	char* page;
	map chains;
	int abandoned;
} mempage;
struct gcdata {
	int total_pages;
	void** stack_head;
	int page_no;
	long long max_used;
	long long curr_used;
	long long max_mem;
	long long curr_mem;
	mempage* pages;
	int gcruns;
	int gcwaste;
	int inalloc;
	int gctime;
	int gcmax;
	struct timeval run_time;
	struct timeval time;
	size_t clockstart;
	int total_time;
};
extern struct gcdata _gcdata;
extern map* _globals;

extern int _printed;
extern int _is_web;

extern char* skip;

#define End (char*)(0x0FF1B14E059AD3BA)

void* php_global(char* name);
int rand();
void* px(void* str, int newline);
void xexit(int val);
void* fox_error(char* msg, int dump);
int mem_total();
int mem_free();
void fox_signal_handler(int sig);
void stack_dump_direct();
char* stack_str();
void fox_stack_dump();
size_t blob_size(char* in);
int str_len(char* str);
char* new_blob(int size);
char* blob_dup(char* str, int len);
char* str_dup_len(char* str, int len);
char* str_dup(char* str);
char* sub_str(char* src, int from, int len);
char* print(char* str, FILE* fp);
char* str_times(char* str, int times);
char* xstr(char* ret, ...);
char* xcat(char* ret, ...);
char* cat(char* str1, char* str2, size_t len);
char* vec_json(map* mp, int indent);
char* json(map* mp, int indent);
char* to_str(void* v, char* null, int human);
char* str_quote(char* head);
char* double_str(double val);
char* int_str(long long value);
int str_eq(char* str, char* str1);
size_t str_hash(unsigned char * str);
map* xvec(void* v1, ...);
map* xmap(char* k1, ...);
char* new_str(int len);
map* new_map();
map* new_vec();
int key_eq(map* mp, int idx, char* id);
int key_hash(char* id);
int map_has_key(map* mp, char* id);
map* vec_realloc(map* mp, int extra);
map* vec_add(map* mp, void* v);
map* set(map* mp, int idx, void* val);
long long is_int(void* v);
double is_double(void* v);
void* int_var(size_t i);
void* double_var(double f);
int has_id(map* mp, int idx);
void* map_idp(map* mp, int idx);
void* map_id(map* mp, int idx);
int map_len(map* mp);
char* map_key(map* mp, int idx);
char* is_str(void* v);
char* is_blob(void* v);
map* is_vec(void* v);
map* is_hash(void* v);
map* is_map(void* v);
double str_double(char* v);
double to_double(void* v);
long long str_int(char* v);
long long to_int(void* v);
int next(map* mp, int idx, char** key, void** val);
int stoi(char* str);
map* globals();
int mem_used(int block_size, int type);
mempage* ptr_page(void* ptr);
void* block_ptr(int block, mempage* pg);
int ptr_block(void* ptr, mempage* pg);
int ptr_type(void* ptr);
int cell2_mark(Mapcell* pairs, int size);
int cell_mark(void** pairs, int size);
int gc_mark(void* ptr);
int sweep_page(mempage* pg);
void* data_delete(void* data, int idx, int size, int len);
void* data_insert(void* data, int idx, int size, int len);
void* data_shift(void* data, int idx, int shift, int size, int len);
int cmp_page(const void* pg1, const void* pg2);
void reindex_pages();
mempage* no_page(int no);
struct mempage* new_page(int block_size, int blocks);
int comp_iptr(const void* sp1, const void* sp2);
mempage* index_free_space(mempage* pg);
void* chain_alloc(mempage* pg, int size, int type, char* ptr);
void* page_alloc(mempage* pg, int size, int type, int* full);
int gc_sweep();
map* root_ptrs();
int fox_gc();
int gc_runs();
int gc_time();
int gc_end();
mempage* free_page(mempage* pg);
int block_len(int block, mempage* pg);
int mem_size(void* ptr);
void* expand_inplace(char* ptr, char type, int size, int extra);
int size_blocks(size_t size, mempage* pg);
void* fox_realloc(void* ptr, size_t size, int type);
void* fox_alloc(size_t size, int type);
void* new_alloc(size_t size, int type);
void* _xalloc(size_t size, int type);
int block_size(int size);
void start_time();
void end_time();
int run_time();
int total_time();
void time_max();
struct timeval microtime();
int elapsed(struct timeval from);
int map_size(map* mp);
int ceil_pow2(int i);
map* add(map* mp, void* k, void* v);
map* vec_set(map* mp, int idx, void* v);
map* map_add(map* mp, char* key, void* v);
int map_nextno(map* mp);
map* map_index(map* mp, int idx);
map* map_reindex(map* mp);
char* null_str(char* in);
map* ptrs_vec(void** ptrs, int len);
int init_gc(void** sp);
int exec(char* cmd, char** output);
size_t clock_cycles();
void* ptr_head(void* ptr);
int block_head(int no, mempage* pg);
void init_rand();
void* map_val(map* mp, char* key);
map* env_vars();
map* argv_map(char** argv, int argc);
char* strstr(const char* str1, const char* str2);
int chdir(const char* path);
void* invoke(map* v, char* name);
map* reflect();
int max_mem();
int curr_mem();
char* version();
map* args_map();
void* call_php(map* params, char* func);
int cgi(char* infile, char* outfile, char* opts, int keepfiles);
char* write_htaccess();
int cc(char* infile, char* outfile, char* profile, char* opts, int keepfiles);
char* file_dir(char* file);
void write_source();
char* file_rename(char* file, char* dir, char* delext, char* addext, char* prefix, char* postfix);
char* sane_dir(char* dir);
char* write_configm4(char* name, char* outfile);
char* mem_usage();
char* int_kb(size_t i, char* unit);
char* int_human(int i, char* unit, char* zero);
char* mstr(char* format, ...);
char* cat_char(char* str, char c);
char* va_str(char* format, va_list args);
void* dx(void* data, char* name, int panic);
int neq(char* str, char* str1);
int eq(char* str, char* str1);
char* cwd();
char* write_file(char* data, char* filename, int readonly, int verbose);
char* file_read(char* filename, int istext, int error_on_fail);
char* read_stdin(int size, char* terminator);
char* str_unquote(char* str);
char* str_escape(char* head);
char* str_end(char* str, char* end);
int str_start(char* str, char* start);
char* str_chr(char* str, char c);
char* str_ltrim(char* str, char* chars);
char* str_rtrim(char* str, char* chars);
char* str_trim(char* str, char* chars);
int line_isempty(char* line);
int line_len(char* line);
int lchars(char* str, char* chars);
int rchars(char* str, char* chars, int off);
int has_str(char* str, char* substr);
char* str_replace(char* str, void* find, void* replace);
char* outx(char* str);
char* flush_out();
map* xadd(map* mp, ...);
int is_numeric(char* str);
map* to_map(void* val);
map* del_index(map* mp, int idx);
map* map_del_key(map* mp, char* key);
map* map_del(map* mp, int idx, int len);
map* xjson_map(char* in, int type);
map* xjson_map_recurse(char** line, int type);
int str_level(char* line);
int block_level(char* str);
void* marked_str(char* str, char* name);
map* map_add_pair(map* mp, void* name, void* value, int type);
map* add_name_val(map* mp, char* str, char** name, char** val, int type);
char* read_as_block(char** from, int level, char* terminator);
map* block_map(char** from, int inlevel, int maptype);
map* xkeys(char* str);
map* xindex(char* str);
map* xarray(char* str);
map* str_vec(void* str);
void cache_blast(char* type);
void* cache(void* key, char* type, void* out);
map* str_map(char* str, int type);
void rewrite_ptr(mempage* pg, void** ptr);
void rewrite_ptrs(mempage* old);
int copy_page(mempage* from, mempage* to);
int page_map(mempage* pg);
int dump_chain(mempage* pg, int line);
int check_chains(mempage* pg, int line);
int total_kb();
int page_maps(char* title);
map* vec_del(map* mp, int from, int len);
map* vec_shift(map* mp, int idx, int len, int offset);
map* vec_sub(map* mp, int from, int len);
map* vec_slice(map* mp, int from, int len);
map* map_splice(map* mp, int from, int del, map* ad);
void* vec_pop(map* mp);
map* vec_splice(map* mp, int from, int del, map* add);
char* str_has(char* str, char* sub);
char* str_str(char* in, char* sub);
void gotoxy(int x, int y);
int floor_pow2(int i);
map* vec_dup(map* mp);
map* map_dup(map* mp);
map* map_merge(map* mp1, map* mp2);
map* vec_merge(map* mp1, map* mp2);
int utest(char* found, char* expect, char* in, char* title);
map* map_compact(map* mp);
map* vec_reverse(map* mp);
map* vec_compact(map* mp);
map* change_key(map* mp, int idx, char* id);
char* old_decl_type(map* mp, int idx);
map* add_id(map* mp, int idx);
map* add_key(map* mp, char* k, int type);
char* str_upper(char* s);
char* str_lower(char* s);
map* str_split(char* str, char* by, int limit);
char* toks_str(map* mp);
char* map_join(map* mp, char* joiner);
char fox_at(char* str, int idx);
char* indent_str(int i);
int str_chars(char* str, char* chars);
char* map_str(map* mp);
char* map_str_indent(map* mp, int indent);
map* dir_files(char* path);
char* end_word(char* str, char* words);
char* has_word(char* str, char* words);
int is_word(char* word, char* list);
int terminate_words(char* in);
map* map_vec(map* mp);
map* toks_keywords(map* mp, char* keywords);
map* map_split(map* mp, char* str, int limit);
size_t file_time(char* file);
int is_number(char c);
int is_alphanum(char c, char* others);
int is_alpha(char c, char* others);
int is_oper(char c);
int str_is_oper(char* str);
int str_is_num(char* str);
int is_code(char* str);
char* read_num(char** in);
char* skip_over(char* in, char* chars);
char* skip_word(char* in, char* seperators);
void* read_value(char** str, char* sep);
char* read_upto(char** in, char* terminators);
char* read_alpha(char** in);
char* fox_read_symbol(char** in);
char* fox_read_oper(char** in, char term);
char* read_upto_word(char** in, char* upto);
char* read_theline(char** in);
char* read_newline(char** in);
char* read_space(char** in, char* spaces);
map* read_data(char** in);
char* read_heredoc(char** in);
char* read_multistr(char** in);
char* read_quote(char** in);
char* xlog(char* str);
char closing_paren(char c);
char char_at(char* str, int i);
char* char_str(char c);
int map_has_word(map* mp, char* str);
int is_keyword(char* str);
char* toks_c(map* mp);
map* add_ctok(void* data, map* mp, int iscode);
map* c_tokenizer(char** line, char term);
int func_dot(map* mp, int idx);
map* multiline_parts(char* str);
map* heredoc_parts(char* str);
map* heredoc_str(map* mp);
map* dot_each(map* mp);
map* map_implode(map* mp, char* joiner);
int tok_indent(char* str);
int has_chars(char* line);
int requires_semicolon(map* mp, int idx);
map* add_semicolon(map* mp, int recurse);
char* hello();
int tok_endl(map* mp, int from);
map* force_curly(map* mp);
map* expand_main(map* mp);
map* add_curly(map* mp, int recursive);
map* dot_key(map* mp);
int str_hasvar(char* in);
char* str_mstr(char* in);
map* xstr_parts(char* in);
char* str_xstr(char* in);
map* str_dollars(map* mp);
map* single_quotes(map* mp);
map* colon_str(map* mp);
map* dot_func(map* mp);
map* map_tox(map* mp);
int stm_start(map* mp, int idx, char* terms);
map* syn_func(map* syn, int with_body);
map* file_callmap(char* filename);
map* func_depend(map* mp, map* ret);
map* func_depends(map* mp);
map* syn_funcs(map* mp, int with_body);
map* file_vec(char* in);
map* file_map(char* in);
map* map_keys(map* mp);
char* drop_right(char* str, char* w);
char* drop_left(char* str, char* w);
map* read_struct(map* toks);
map* c_structs(char* in);
map* x_funcs(char* in, int with_body);
map* x_toks(char* in, int is_script);
map* func_params(map* func);
map* func_param(map* func);
map* func_add_param(map* func, map* add);
map* func_rename(map* func, char* name);
char* func_name(map* func);
map* map_assign(map* exp1, map* exp2);
map* call_count(map* toks, map* counter, char* infunc);
map* file_deadcode(char* file);
map* auto_types(map* toks, char* context, int is_script, map* env, map* fns, map* func, int idx);
char* is_typecast(map* toks, int idx);
char* is_name(char* in);
char* head_type(map* toks, int idx, int upto, map* env, map* fs);
int expr_tail(map* toks, int idx, char* expr);
int expr_head(map* toks, int idx, char* expr);
map* add_return(map* toks);
map* wrap_call(map* tok, char* func);
map* type_convert(map* tok, char* outtype, map* env, map* fs, map* fn);
map* param_c(map* params, map* env, map* fs, map* fn);
map* syn_expand_macro(map* syn, int idx);
map* syn_is_macro(map* syn, int idx);
map* syn_set_param(map* syn, int idx, map* params);
map* syn_func_param(map* syn, int idx);
map* syn_func_body(map* syn);
map* syn_remove_default(map* syn);
char* expr_type(map* toks, int idx, int upto, map* env, map* fs);
char* assign_to_func(map* tok);
int next_tok(map* toks, int from, char* tok, int upto);
int syn_has(map* syn, char* words);
char* syn_flow_name(map* syn);
int is_flow(map* syn);
map* syn_flow_condition(map* syn, int no);
map* syn_flow_body(map* syn, int no);
char* syn_is_call(map* syn, int idx);
char* syn_var_name(map* syn);
char* syn_var_type(map* syn);
int syn_assign_val(map* syn);
int is_assign(map* syn);
int is_var_decl(map* syn);
int is_func_decl(map* syn);
char* c_h(char* infile, char* outfile);
char* fox_h(char* infile, char* outfile);
char* fox_c(char* infile, char* outfile);
map* x_map(char* in);
char* c_x(char* in);
char* x_c(char* in);
char* func_ccall(map* fn);
char* map_ccode(void* mp);
char* callfunc_c(map* funcs);
char* file_foxh(char* infile, char* outfile);
char* func_cdecl(map* fn, int show_default);
char* funcs_cdecl(map* fns, int show_default);
char* foxh();
char* write_foxh(char* outfile);
char* fox_phpc(char* infile, char* outfile);
char* write_phpconfig();
char* funcs_meta(map* funcs, char* prefix);
map* eval_params(map* sent, char* name, map* env);
char* to_c(void* val);
char* str_shorten(char* in, int max);
char* call_c(map* params, char* name);
void* call_func(map* params, char* name, map* env);
void* data_exec(void* data, map* env);
static void* eval_toks(map* mp, map* env);
static void* eval_expr(map* mp, int* idx, map* env, int level);
void* eval(char* in, map* env);
int eval_expr_cont(map* mp, int idx, map* env, void** last, int level);
void* binary_op(void* left, char oper, void* right);
int is_true(void * val);
char* read_line(FILE* fp);
char* skip_paren(char* str);
char* skip_quote(char* str);
char* str_toupper(char* str);
char* str_tolower(char* str);
char* str_title(char* str);
char hex_char(char* in);
char* rand_str(int len);
int str_char_count(char* str, char c);
char* write_c(char* infile, char* outfile);
map* command_line(char* in, int argc, char** argv);
map* param_test(char* one, char* two);
map* cmdline_params(map* args, char* func);
int test_add(int a, int b);
map* test_map(map* out);
int utests(char* test, char* file);
char* file_path(char* file);
map* load_global(char* file);
int err_msg(char* msg, char** ptr);
char* tutorial();
char* h(char* in);
char* type_name(int type);
char* ptr_name(void* var);
int is_file(char* filename);
char* fork_exec(char* cmd, map* params);
map* source_files();
map* source_funcs();
map* file_funcs(char* filename, int withbody);
char* help();
map* funcs();
void* fox_run(char* in);
void* fox_eval(map* mp, map* env, int* halt);
void src(map* mp, int from, int len, char* msg);
map* structs();
map* macros();
map* source_structs();
map* source_macros();
int fib(int i);
map* toks_syn(map* toks, int recurse);
time_t str_time(char* in);
char* time_str(time_t timer);
char* tz_dst(char* tz, char* date);
double tz_offset(char* tz, char* date);
char* tz_utc(char* tz, char* date);
char* increase_version();
int call_variadic_int(map* mp, void* fp, char* name);
void* call_variadic_ptr(map* mp, void* fp, char* name);
map* vec_rdup(map* mp);
map* toks_replace(map* in, map* replace);
map* toks_join(map* in, char* by);
map* toks_align(map* in);
map* toks_split(map* in, char* by, int limit);
map* expand_macros(map* mp, map* macros);
map* c_macros(char* in);
map* toks_macros(map* mp);
int is_inline_vector(map* toks, int idx);
map* string_operators(map* toks);
map* inline_vectors(map* toks);
int msleep(int msecs);
char* time_ago(char* stime);
char* ptr_id(void* ptr);
char* today();
char* now();
int this_year();
char* datetime();
int str_ascii(char* in);
void benchmark_gc();
char* ping(char* str);
map* ping_map(map* in);
char* str_join(char* str1, char* joiner, char* str2);
map* read_paren(map* mp, char** line, map*(*func)(char** ));
map* set_map(void* val, map* mp, int idx);
char* var_bits(void* var);
char* rtrim_upto(char* in, char upto, int keep);
map* data_toks(char* in);
map* data_tokenizer(char** in, int level);
char* read_over(char** in, char* chars);
map* data_quote(char* in);
map* prop_vec_toks(char* in);
map* prop_toks(char* in, map* name);
map* split_by(char* str, char term, int max);
char* str_hex(char* in);
char* c_md5(char* in, size_t initial_len, char* out);
char* md5(char* in);
map* data_map(char* in);
map* data_map2(char** in, int level);
char* skip_code(char* in, char* terminator);
char* skip_upto(char* in, char* chars);
void* data_unquote(char* in);
map* prop_vec(char* in);
map* prop_map(char* in, char* name);
int utf_strlen(char* in);
char* unicode_utf(int ucs2, char* ret);
int utf_len(char* in);
int utf_unicode(char* ptr);
char* num_lang(char* in, char* lang);
char* str_tr(char* in, map* replace);
map* sql_toks(char* line);
map* split_keywords(map* mp, char* words);
void* key_var(char* key);
map* map_key_val(map* mp, int idx);
char* join_clause(char* pre, map* mp, char* clause, char* by, char* sub1, char* sub2, char* use_cls);
map* de_select(map* cls);
map* de_from(map* cls);
map* parse_where(map* cls);
map* de_where(map* cls);
map* de_having(map* cls);
map* de_order(map* cls);
map* de_group(map* cls);
map* de_limit(map* cls);
map* sql_toks_map(map* toks);
map* sql_map(char* sql);
char* sql_map_join(map* mp, char* joiner);
char* var_join(void* v, char* joiner);
map* sql_convert_func(map* mp, char* db);
char* is_func(map* mp, int idx);
map* sql_func_params(map* mp, int idx);
map* get_func(map* mp, int idx);
map* search_sql_func(map* mp, char* db);
map* to_vec(void* val);
map* sql_order(char* sql);
map* sql_tables(char* sql, char* db);
map* sql_col(char* sql, char* db, map* exp);
char* str_code(char* in);
map* crosstab_cols(map* cols, char* sql, char* db, map* params);
map* sql_select_cols(char* sql, char* db, map* params);
char* sql_add_where(char* sql, map* mp);
map* cols_collect(map* cols, void* collect);
map* sql_where_cols(char* sql, char* db);
map* sql_where_vals(char* sql);
char* sql_add_limit(char* sql, int rpp, int page);
char* sql_add_order(char* sql, char* db, map* order);
char* sql_add_filter(char* sql, map* filter);
char* name_type(char* name);
map* to_cols(void* cols, char* sql, char* db);
map* sql_cols(char* sql, char* db, void* cols);
map* sql_add_cols(char* sql, char* db, map* cols);
map* sql_view_cols(char* sql, char* db, map* cols);
map* sql_edit_cols(char* sql, char* db, map* cols);
map* sql_list_cols(char* sql, char* db, map* cols);
char* sql_add_cls(char* sql, char* cls, map* vals);
map* sql_cls(char* sql, char* cls);
char* sql_str(void* data);
char* re_select(map* mp);
char* re_from(map* cls);
char* re_where(map* cls);
char* re_group(map* cls);
char* re_having(map* cls);
char* re_order(map* cls);
char* re_union(map* cls);
char* re_limit(map* cls);
char* map_sql(map* mp);
int has_aggregate(char* sql);
char* sql_auto_join(char* sql, char* db);
char* sql_auto_group(char* sql, char* db);
char* sql_lite(char* sql, char* db, map* params);
int sql_utest(char* in, char* out);
int type_size(char* type);
char* lite_create_col(map* col);
int is_indexed(char* type);
map* trigger_sqls(char* tbl, char* db);
map* tbl_trigger_sqls(map* tbl);
map* create_index_sqls(map* tbl);
char* drop_sql(char* name);
char* create_sql(map* tbl, char* name);
char* meta_type(char* type, int size);
int has_table(char* db, char* tbl);
map* map_cols(void* cols, char* tbl, char* db);
map* cols_table(map* cols, char* tbl, char* db);
map* pre_tables();
map* db_table(char* db, char* tbl);
map* db_tables(char* db);
map* db_cols(char* db, char* tbl);
map* url_gets();
char* sql_table(char* sql);
map* sql_pkeys(char* sql, char* db);
void* sql_value(char* sql, char* db, map* param);
map* sql_rows(char* sql, char* db, map* param);
map* sql_query(char* sql, char* db, map* where);
map* tbl_id_ids(char* tbl, char* db, void* id);
map* sql_row(char* sql, char* db, map* param);
map* sql_vector(char* sql, char* db, map* param);
map* sql_pairs(char* sql, char* db, map* param);
map* sql_vec(char* sql, char* db, map* param);
char* sql_drop(char* tbl);
char* to_sql(char* sql);
map* meta_fkeys(char* db);
map* tbl_referred_by(char* tbl, char* db);
void* id_update(void* ids, char* tbl, char* db, map* row);
int row_insert(map* row, char* tbl, char* db);
void* sql_error(char* sql, char* db, sqlite3* conn);
map* sqls_exec(map* sqls, char* db);
map* parse_connection(char* in);
map* conn_db(char* db);
map* sql_exec(char* sql, char* db, map* params);
void* lite_conn(char* db);
map* lite_exec(char* sql, char* db, map* params);
void close_conns();
map* vec_map(map* in);
map* db_table_names(char* db);
map* cols_pkeys(map* cols);
map* crud_save(char* sql, char* db, map* cols, char* back, map* data);
map* types();
char* maptype(map* mp, char* type);
map* where_param(map* where);
map* where_rows(map* where, char* tbl, char* db);
map* where_row(map* where, char* tbl, char* db);
map* id_row(char* id, char* tbl, char* db);
map* ids_row(map* ids, char* tbl, char* db);
map* ids_param(map* ids, char* tbl, char* db);
map* tbl_pkeys(char* tbl, char* db);
map* tbl_skeys(char* tbl, char* db);
map* cols_skeys(map* cols);
map* toks_sql_params(map* toks, map* ret);
void* is_null(void* val);
map* sql_missing_params(char* sql, map* params);
map* fkey_list(char* sql, char* db, map* params);
map* sql_params(char* sql);
char* fkey_sql(char* sql, char* db);
char* callback_php(map* param, char* name);
char* fkey_show(char* sql, char* db, char* id);
int fkey_valid(char* sql, char* db, char* id);
char* str_show(char* value, char* type, map* op, int width);
char* cols_show(map* cols, map* row, char* name, int width);
char* datetime_human(char* in);
char* thumb_name(char* name);
map* row_show(map* row, map* cols, int width);
map* rows_show(map* rows, map* cols, int width);
void* sql_delete(void* ids, char* tbl, char* db);
char* sql_rename(char* from, char* into);
map* subtypes(char* type);
int type_distance(char* type1, char* type2);
map* cols_match(map* from, map* into);
char* month_name(int month);
int cmp_ptr_reverse(const void* ptr1, const void* ptr2);
int cmp_ptr(const void* ptr1, const void* ptr2);
int cmp_cons_reverse(const void* ptr1, const void* ptr2);
int cmp_cons(const void* ptr1, const void* ptr2);
map* map_sort(map* mp, int reverse);
char* nearest_table(map* tbls, map* tbl);
map* tbls_sync_sqls(map* new_tbls, map* old_tbls);
map* db_meta(char* db);
map* tbl_cols(char* table, char* db);
map* db_sync(char* db, int go);
map* sync_sqls(map* newt, map* oldt);
char* test_out(char* in);
map* sql_sums(char* sql, char* db, map* cols, map* params);
int sql_count(char* sql, char* db, map* params);
map* regexp(char* in, char* pattern);
char* read_textblock(map* lines, int* lineno, char* terminator, char** outline);
char* http_moved(char* url);
char* http_redirect(char* url);
void* http_error(char* msg, char* status);
char* file_mime(char* path);
char* str_html(char* in);
void header(char* str);
char* http_out(char* str, char* status, char* mime, map* headers);
char* static_file(char* path);
char* str_url(char* in);
char* url_str(char* in);
char* map_amps(void* val, char* name);
map* amps_map(char* in);
map* parse_url(char* path);
char* url_host(char* url);
map* sess_init();
void sess_add(char* name, char* value);
char* sess_id();
char* sess_file();
char* sess_newid();
void cookie_set(char* name, char* value, char* path, char* expire);
void sess_delete();
map* link_relative(map* links, char* url);
map* header_map(char* val);
map* http_req();
int ip_connect(char* host, int port, char** err);
int ip_close(int sock);
int ip_send(char* msg, int sock);
char* ip_receive(int sock, char* terminator, int size);
char* remote_ip(int con);
map* sql_tokenizer(char** line);
map* prop_tokenizer(char** line);
map* tokenizer(char** line, char* comment);
char* md_url(char* in, int len, void* junk);
char* file_markdown(char* infile, char* outfile);
char* fox_markdown(char* in);
size_t fox_curl_cat(void* ptr, size_t size, size_t num, void* old);
char* fox_curl(char* url);
char* full_url(char* url);
char* url_abs(char* abs, char* rel);
char* base_url(char* path);
char* home_url(char* path);
char* show_port();
map* lite_trigger_slno(char* name, char* pkey, char* by);
map* lite_trigger_tree(char* name, char* pkey);
char* page_html(map* data);
map* page_data(map* data);
int not_found(char* path);
int show_page(map* data);
int is_post();
map* post_data();
char* name_tab(char* name);
map* get(char* path, map* names);
void show_body(char* body, map* page);
int days_in_feb(int year);
int days_in_month(int month, int year);
char* add_tab(char* path, char* name);
double circular(double v, double from, double upto);
double jd3(int y, int m, double d);
double year(double jd);
double jd_month(double jd);
double delta_t(double jd);
double delta_t2(double jd);
double julian_centuries(double jd);
double sun_mean_lng(double t);
double sun_mean_ano(double t);
double sun_mean_ano5(double t);
double ecentricity(double t);
double _ceil(double value);
double sind(double v);
double cosd(double v);
double tand(double v);
double asind(double v);
double acosd(double v);
double atand(double v);
double atand2(double y, double x);
double round2(double v, double d);
double ahavd(double v);
double havd(double v);
double bearing(double lng1, double lat1, double lng2, double lat2);
double diff_angle(double lng1, double lat1, double lng2, double lat2);
double diff_angle2(double lng1, double lat1, double lng2, double lat2);
double moon_mean_lng(double t);
double moon_mean_elong(double t);
double moon_mean_ano(double t);
double moon_arg_lat(double t);
double sun_eqn(double t, double meanano);
double refraction(double alt);
double refraction2(double alt, double temp, double press);
double parallax_au(double alt, double r);
double parallax(double alt, double r);
double dip(double height);
double geodetic(double lat);
double moon_mean_node_lng(double t);
double nutation_obl(double t);
double nutation_lng(double t);
double sidereal4(double jd);
double az(double lha, double dec, double lat);
double alt(double lha, double dec, double lat);
double sun_lng4(double t);
double sun_ano4(double t);
double sun_r(double t);
double dms(double d, double m, double s);
double obl4(double t);
double ra(double lng, double lat, double obl);
double decli(double lng, double lat, double obl);
double sun_semi_dia(double t);
double moon_semi_dia(double t);
double moon_month_phase(double t);
double moon_visual_phase(double t);
double moon_lng4(double t);
double moon_lat4(double t);
double moon_r(double t);
double moon_mean_phase(double k, double t);
double is_eql(double v1, double v2, double maxdiff);
double lunation_date(double lun);
double lha(double ra, double sidereal, double lng);
double cos_ha(double alt, double decl, double lat);
double alt_ha(double alt, int direction, double dec, double lat);
double rise_set(double jd, double t, double elng, double elat, double alt, int direction, double lng, double lat);
double sun_transit(double jd, double lng, double lat);
double sun_rise_set(double alt, int direction, double jd, double lng, double lat);
double moon_rise_set(double alt, int direction, double jd, double lng, double lat);
double sun_rise(double jd, double lng, double lat);
double sun_set(double jd, double lng, double lat);
double moon_rise(double jd, double lng, double lat);
double moon_set(double jd, double lng, double lat);
double sun_ra(double t);
double sun_dec(double t);
double moon_ra(double t);
double moon_dec(double t);
double sun_az(double jd, double lng, double lat);
double sun_alt(double jd, double lng, double lat);
double moon_az(double jd, double lng, double lat);
double moon_alt(double jd, double lng, double lat);
double moon_position_angle(double t);
double moon_zenith_angle(double jd, double lng, double lat);
double yallop_best_time(double jd, double lng, double lat);
double arcl(double jd, double lng, double lat);
double arcv(double jd, double lng, double lat);
double moon_pi(double t);
double angle_sun_moon(double t);
char* yallop_name(int zone);
double translate_yallop_q(double q);
double yallop_q2(double moon_alt, double arc_light, double arc_vision, double moon_r);
double yallop_q(double jd, double lng, double lat);
int hijri_year(int lun);
int hijri_month(int lun);
double lunation(double jd);
double new_moon(double lun);
double full_moon(double lun);
double moon_phase_angle(double t);
double moonmag(double t);
double moon_mag3(double phaseangle);
double moon_mag4(double dist, double phase);
double moon_mag2(double t);
int array_seek(char** arr, char* val);
void hijri_month_cache_bd();
void hijri_month_cache();
double dhaka_lng();
double dhaka_lat();
double kaba_lng();
double kaba_lat();
double kaba_sun_set(double jd);
double kaba_moon_set(double jd);
double hijri_month_length(int lun);
double hijri_month_length_bd(int lun);
double hijri_month_start3(int lun);
double hijri_month_start_bd3(int lun);
double hijri_month_start_bd(int lun);
double hijri_month_start(int lun);
double hijri_month_start_bd2(int lun);
double kaba_tz();
double hijri_month_start75(int lun);
double hijri_month_start2(int lun);
double hijri_lunation_bd(double jd);
char* hijri_date_bd(double jd);
double hijri_lunation(double jd);
double current_hijri_month_bd();
double current_hijri_month();
double current_hijri_year();
double jd_now();
char* hijri_now(double tz);
char* hijri_now_bd(double tz);
double hijri_day_bd(double jd);
double hijri_day(double jd);
double hijri2jd(int y, int m, int d);
char* hijri_date(double jd, double tz);
double jd(char* date, double tz);
char* jd_str(double jd, double tz);
double frac(double val);
char* jdstring_ar(double jd, double tz);
char* jdstring_bg(double jd, double tz);
char* date_only(char* in);
char* jd_human(double jd, double tz);
char* wday_en(int val);
char* wday_en3(int val);
char* month_bg3(int val);
char* month_bg(int val);
char* ar_wday(int wday);
char* wday_bg(int wday);
char* month_ar(int month);
char* month_en(int val);
char* month_en3(int val);
char* astro_nth(int n);
int cemonth(int ym);
int ceyear(int ym);
char* hijri_month_name_bg(int v);
char* hijri_month_name_ar(int v);
char* hijri_month_name(int v);
int jd_wday(double jd, double tz);
double tz();
void rgb2hsl(int r, int g, int b, double* out_h, double* out_s, double* out_l);
double jday(double jd);
char* bearing_name3(double lng1, double lat1, double lng2, double lat2);
char* bearing_name(double lng1, double lat1, double lng2, double lat2);
static double hue_2_rgb(double v1, double v2, double v_h);
void hsl2rgb(double h, double s, double l, int* ret_r, int* ret_g, int* ret_b);
map* salat_time(double jd, double lng, double lat);
double esha(double jd, double lng, double lat);
double fajar18(double jd, double lng, double lat);
double noon(double jd, double lng, double lat);
double asar2(double jd, double lng, double lat);
double asar1(double jd, double lng, double lat);