#include <fox.h>
void hijri_month_cache_bd();
void hijri_month_cache();
double dhaka_lng();
double dhaka_lat();
double kaba_lng();
double kaba_lat();
double kaba_sun_set(double jd);
double kaba_moon_set(double jd);
double hijri_month_length(int lun);
double hijri_month_length_bd(int lun);
double hijri_month_start3(int lun);
double hijri_month_start_bd3(int lun);
double hijri_month_start_bd(int lun);
double hijri_month_start(int lun);
double hijri_month_start_bd2(int lun);
double kaba_tz();
double hijri_month_start75(int lun);
double hijri_month_start2(int lun);
double hijri_lunation_bd(double jd);
char* hijri_date_bd(double jd);
double hijri_lunation(double jd);
double current_hijri_month_bd();
double current_hijri_month();
double current_hijri_year();
double jd_now();
char* hijri_now(double tz);
char* hijri_now_bd(double tz);
double hijri_day_bd(double jd);
double hijri_day(double jd);
double hijri2jd(int y, int m, int d);
char* hijri_date(double jd, double tz);
double jd(char* date, double tz);
char* jd_str(double jd, double tz);
double frac(double val);
char* jdstring_ar(double jd, double tz);
char* jdstring_bg(double jd, double tz);
char* date_only(char* in);
char* jd_human(double jd, double tz);
char* wday_name2(int val);
char* wday_name(int val);
char* month_name3bg(int val);
char* month_name_bg(int val);
char* ar_wday(int wday);
char* bg_wday(int wday);
char* ar_month(int month);
char* bg_month(int month);
char* en_month(int val);
char* month_name3(int val);
char* astro_nth(int n);
int cemonth(int ym);
int ceyear(int ym);
char* hijri_month_name_bg(int v);
char* hijri_month_name_ar(int v);
char* hijri_month_name(int v);
int jd_wday(double jd, double tz);
double tz();
void rgb2hsl(int r, int g, int b, double* out_h, double* out_s, double* out_l);
double jday(double jd);
char* bearing_name3(double lng1, double lat1, double lng2, double lat2);
char* bearing_name(double lng1, double lat1, double lng2, double lat2);
static double hue_2_rgb(double v1, double v2, double v_h);
void hsl2rgb(double h, double s, double l, int* ret_r, int* ret_g, int* ret_b);
map* salat_time(double jd, double lng, double lat);
double esha(double jd, double lng, double lat);
double fajar18(double jd, double lng, double lat);
double fajar15(double jd, double lng, double lat);
double noon(double jd, double lng, double lat);
double asar2(double jd, double lng, double lat);
double asar1(double jd, double lng, double lat);