#include <fox.h>
#include "habib.h"

extern map* _globals;

void* sql_item_type(char* type, char* db){
	return sql_pairs("select name,data from __item where type=:type and module=:module",map_val(sql_conn(db),"ddb"),xmap("type", type, "module", map_val(sql_conn(db),"module"), End));
};
void* sql_item(char* name, char* type, char* db){
	return sql_value("select data from __item where name=:name and type=:type and module=:module",map_val(sql_conn(db),"ddb"),xmap("name", name, "type", type, "module", map_val(sql_conn(db),"module"), End));
};
void* fetch_global(char* in){
	return php_global(in);
};
map* sql_conn(char* name){
	if(!name){ name=map_key(map_val(_globals,"dbs"),0); };
	if(!is_code(name)){ return parse_connection(name); };
	if(!map_val(_globals,"dbs")){
		map* dbs=php_global("_dbs");
		for(int next1=next(dbs,-1,NULL,NULL); has_id(dbs,next1); next1++){ void* val=map_id(dbs,next1); char*  key=map_key(dbs, next1);
			add(add_key(_globals,"dbs",Map),key,parse_connection(val));
			add(add_key(add_key(_globals,"dbs",Map),key,Map),"id",key); }; };
	return map_val(map_val(_globals,"dbs"),name);
};
//map* read_paren(map* mp, char** line, map*(*func)(char** ));
//map* sql_tokenizer(char** line);
//map* sql_toks(char* line);
//map* split_keywords(map* mp, char* words);
//char* str_join(char* str1, char* joiner, char* str2);
//void* key_var(char* key);
//map* map_key_val(map* mp, int idx);
//char* join_clause(char* pre, map* mp, char* clause, char* by, char* sub1, char* sub2, char* use_cls);
//map* de_select(map* cls);
//map* de_from(map* cls);
//map* parse_where(map* cls);
//map* de_where(map* cls);
//map* de_having(map* cls);
//map* de_order(map* cls);
//map* de_group(map* cls);
//map* de_limit(map* cls);
//map* sql_toks_map(map* toks);
//map* sql_map(char* sql);
//char* sql_map_join(map* mp, char* joiner);
//char* var_join(void* v, char* joiner);
//map* sql_convert_func(map* mp, char* db);
//char* is_func(map* mp, int idx);
//map* sql_func_params(map* mp, int idx);
//map* get_func(map* mp, int idx);
//map* search_sql_func(map* mp, char* db);
//map* to_vec(void* val);
//map* sql_order(char* sql);
//map* sql_tables(char* sql, char* db);
//map* sql_col(char* sql, char* db, map* exp);
//char* str_code(char* in);
//map* crosstab_cols(map* cols, char* sql, char* db, map* params);
//map* sql_select_cols(char* sql, char* db=NULL, map* params=NULL);
//char* sql_add_where(char* sql, map* mp);
//map* cols_collect(map* cols, void* collect);
//map* sql_where_cols(char* sql, char* db);
//map* sql_where_vals(char* sql);
//char* sql_add_limit(char* sql, int rpp=200, int page=0);
//char* sql_add_order(char* sql, char* db, map* order=NULL);
//char* sql_add_filter(char* sql, map* filter);
//char* name_type(char* name);
//map* to_cols(void* cols, char* sql=NULL, char* db=NULL);
//map* sql_cols(char* sql, char* db, void* cols=NULL);
//map* sql_add_cols(char* sql, char* db, map* cols=NULL);
//map* sql_view_cols(char* sql, char* db, map* cols=NULL);
//map* sql_edit_cols(char* sql, char* db, map* cols=NULL);
//map* sql_list_cols(char* sql, char* db, map* cols=NULL);
//char* table_name(char* tbl, char* db);
//char* sql_add_cls(char* sql, char* cls, map* vals);
//map* sql_cls(char* sql, char* cls);
//char* sql_str(void* data);
//char* re_select(map* mp);
//char* re_from(map* cls);
//char* re_where(map* cls);
//char* re_group(map* cls);
//char* re_having(map* cls);
//char* re_order(map* cls);
//char* re_union(map* cls);
//char* re_limit(map* cls);
//char* map_sql(map* mp);
//int has_aggregate(char* sql);
//char* sql_auto_join(char* sql, char* db=NULL);
//char* sql_auto_group(char* sql, char* db=NULL);
//char* sql_lite(char* sql, char* db=NULL, map* params=NULL);
//int sql_utest(char* in, char* out);
//int type_size(char* type);
//char* lite_create_col(map* col);
//int is_indexed(char* type);
//map* create_index_sqls(map* tbl);
//char* drop_sql(char* name);
//char* create_sql(map* tbl, char* name=NULL);
//char* meta_type(char* type, int size);
//int has_table(char* db, char* tbl);
//map* map_cols(void* cols, char* tbl, char* db);
//map* cols_table(map* cols, char* tbl, char* db);
//map* tables(char* db);
//int db_has_schema(char* db);
//map* tbl_cols(char* tbl, char* db);
//map* table(char* tbl, char* db);
//map* schema_tables(char* db);
//map* schema_table(char* db, char* tbl);
//map* db_table(char* db, char* tbl);
//map* db_tables(char* db);
//map* db_cols(char* db, char* tbl);
//map* row_ids(void* row, char* tbl, char* db);
//map* pkeys_where(char* tbl, char* db);
//map* tbl_row_ids(char* tbl, char* db, map* row);
//char* tbl_row_id(char* tbl, char* db, map* row);
//char* ids_id(map* ids);
//map* url_gets();
//map* get_ids(char* tbl, char* db);
//char* sql_table(char* sql);
//map* sql_pkeys(char* sql, char* db);
void* sql_value(char* sql, char* db, map* param);
map* sql_rows(char* sql, char* db, map* param);
//map* sql_query(char* sql, char* db, map* where=NULL);
//map* tbl_id_ids(char* tbl, char* db, void* id);
//map* sql_id_ids(char* sql, char* db, void* id);
//map* sql_id(char* sql, char* db, void* ids);
//map* sql_row(char* sql, char* db, map* param=NULL);
//map* sql_vector(char* sql, char* db, map* param=NULL);
map* sql_pairs(char* sql, char* db, map* param);
//map* sql_vec(char* sql, char* db, map* param=NULL);
//char* sql_drop(char* tbl);
//char* to_sql(char* sql);
//map* schema_fkeys(char* db);
//map* tbl_referred_by(char* tbl, char* db);
//void* id_update(void* ids, char* tbl, char* db, map* row);
//map* row_insert(map* row, char* tbl, char* db);
//void* sql_error(char* sql, char* db, sqlite3* conn);
//map* sqls_exec(map* sqls, char* db);
//char* db_conn(char* db);
//map* lite_exec(char* sql, char* db, map* params=NULL);
map* db_table_names(char* db);
//map* schema_table_names(char* db);
//map* user_tables(map* tbls);
//map* table_names(char* db);
//char* col_title(map* col);
//map* cols_pkeys(map* cols);
//map* crud_save(char* sql, char* db, map* cols, char* back, map* data);
//char* maptype(char* type_map, char* type);
//map* tbl_pkeys(char* tbl, char* db);
//map* tbl_skeys(char* tbl, char* db);
//map* cols_skeys(map* cols);
//map* toks_sql_params(map* toks, map* ret={});
////void* is_null(void* val);
//map* sql_missing_params(char* sql, map* params);
//map* fkey_list(char* sql, char* db, map* params=NULL);
//map* sql_params(char* sql);
//char* fkey_sql(char* sql, char* db);
//char* callback_php(map* param, char* name);
//char* fkey_show(char* sql, char* db, char* id);
//int fkey_valid(char* sql, char* db, char* id);
//char* str_show(char* value, char* type, map* op=NULL, int width=0);
//char* thumb_name(char* name);
//map* row_show(map* row, map* cols, int width=2);
//map* rows_show(map* rows, map* cols, int width=2);
//char* cols_show(map* cols, map* row, char* name, int width=2);
//char* buttons_html(map* buttons);
//map* cols_list(map* cols, char* crud=NULL, int max=12);
//map* map_table(map* mp, char* tbl, char* db);
//map* table_map(map* tbl);
//map* tables_map(map* tbls);
//char* db_file(char* db, char* file);
//char* schema_file(char* db, char* file=NULL);
//map* file_compile(char* file, char* db, int go=0);
//char* file_schema(char* file, char* db);
//char* init_schema(char* db);
//char* db_schema(char* db);
//char* crud_tables(char* db);
//char* crud_list(char* sql, char* db, int limit=50, char* crud=NULL);
//char* confirm(char* prompt=NULL, char* option1=NULL, char* option2=NULL, char* title="Confirm", map* data=NULL);
//char* sql_delete(void* ids, char* tbl, char* db);
//char* crud_delete(char* sql, char* db=_globals.ddb, char* back="../");
//char* edit_schema(char* sql, char* db=_globals.ddb, map* cols=NULL, char* back="../");
//char* crud_add(char* sql, char* db=_globals.ddb, map* cols=NULL, char* back="../");
//char* crud_edit(char* sql, char* db=_globals.ddb, map* cols=NULL, char* back="../");
//char* render_table(map* rows, map* cols, char* sql="", char* crud=NULL);
//char* cols_html(map* cols, map* buttons, char* title=NULL, map* vals=NULL, map* errs=NULL);
//char* rename_sql(char* from, char* into);
//map* save_schema(char* db, char* tbl, map* data);
//map* cols_ctrls(map* cols, map* vals=NULL, map* errs=NULL);
//map* subtypes(char* type);
//int type_distance(char* type1, char* type2);
//map* cols_match(map* from, map* into);
//map* schema_list(char* db, char* type);
//map* schema_item(char* db, char* type, char* name);
//char* month_name(int month);
//char* date_show(char* in);
//void* crud(char* sql=NULL, char* db=_globals.ddb, map* cols=NULL, char* crud=NULL, int limit=50, void* link=NULL, char* rest=NULL, char* table=NULL);
//int cmp_ptr_reverse(const void* ptr1, const void* ptr2);
//int cmp_ptr(const void* ptr1, const void* ptr2);
//int cmp_cons_reverse(const void* ptr1, const void* ptr2);
//int cmp_cons(const void* ptr1, const void* ptr2);
//map* map_sort(map* mp, int reverse=0);
//char* nearest_table(map* tbls, map* tbl);
//map* tbls_sync_sqls(map* new_tbls, map* old_tbls);
//map* schema_sync_db(char* file, char* db, int go=0);
//map* file_tables(char* file);
//map* file_sync_schema(char* file, char* db, int go=0);
//map* file_sync_db(char* file, char* db, int go=0);
//map* sync_sqls(map* newt, map* oldt);
//int utf8_strlen(char* in);
//int ucs2_to_utf8(int ucs2, char* utf8);
//int utf8_to_ucs2(char** end_ptr);
//char* test_out(char* in);
//map* sql_sums(char* sql, char* db, map* cols, map* params);
//int sql_count(char* sql, char* db, map* params=NULL);
//char* read_token(char** line, char* terminators=" \t");
//char* read_textblock(map* lines, int* lineno, char* terminator, char** outline);
//map* mml_map(map* lines, int* from=NULL);
//char* val_eval(void* in, map* params=NULL, int is_code=0);
//char* load_mml(char* name);
//char* map_html(map* in, map* params=NULL);
//char* mml_html(char* str, map* params=NULL);
//map* show_map(char* show);
//char* data_show(map* data, char* show);
//char* http_redirect(char* url);
//void* http_error(char* msg, char* status);
//map* compile_template(char* tem);
//char* render_template(map* data, char* template_name);
//char* render(map* data, void* tem);
//char* render_data(void* data, map* tp, char* key);
//char* file_mime(char* path);
//char* str_html(char* in);
//void header(char* str);
//char* http_out(char* str=NULL, char* status="200 OK", char* mime="text/html; charset=utf-8", map* headers=NULL);
//char* static_file(char* path);
//char* str_url(char* in);
//char* url_str(char* in);
//map* amps_map(char* in);
////map* parse_url(char* path);
//void load_theme(char* name=:dashboard);
//void sess_load();
//void sess_add(char* name, char* value);
//char* sess_id();
//char* sess_file();
//void init_rand();
//char* sess_newid();
//void cookie_set(char* name, char* value, char* path="/", char* expire=NULL);
//void sess_delete();
//map* link_relative(map* links, char* url);
//char* links_ul(map* mp, char* class=NULL);
//map* post_data();
//char* button_clicked(map* process);
//map* process_post(map* process);
//char* process_logout(char* redirect="../login/");
//map* process_login(char* username, char* password);
//char* page_set_cookie();
//char* page_dump();
//map* url_data(char* url, char* match);
//map* path_params(char* url, char* path);
//int path_matches(char* match, void* url);
//char* pages_match(map* pages, char* path);
//void* pages_exec(void* pages, char* path, map* env=NULL);
//char* not_found(char* path);
//char* dispatch(map* pages, char* path);
//char* inet(map* pages, char* path=NULL);
//char* page(void* body, char* title, int width=3, void* link=NULL, char* theme=:dashboard, char* pg=:page, map* process=NULL, map* env={});
//char* map_template(map* mp, char* template);
//map* str_vars(char* str);
//char* str_subst(char* in, map* data);
//void* map_eval(void* mp, map* env);
//char* str_eval(char* in, map* env);
//map* header_val(char* line, map* mp);
//map* header_vals(char* name);
//map* header_map(char* val);
//map* read_http_header();
//int ip_connect(char* host, int port, char** err=NULL);
//int ip_close(int sock);
//int ip_send(char* msg, int sock);
//char* ip_receive(int sock, char* terminator, int size);
//char* remote_ip(int con);
